image: webdevops/php-dev:7.4

stages:
  - build
  - test

build:
  stage: build
  script:
    - "composer install --no-progress --optimize-autoloader --prefer-dist"
  artifacts:
    expire_in: 1h
    paths:
      - .Build/

test:
  stage: test
  needs:
    - build
  dependencies:
    - build
  script:
    - "XDEBUG_MODE=coverage .Build/bin/phpunit -c phpunit.xml --coverage-text --colors=never"