services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Fr\MyraCloud\:
    resource: '../Classes/*'
    exclude: ['../Classes/Domain/{DTO,Enum}']

  Fr\MyraCloud\Service\MyraCacheService:
    public: true

  Fr\MyraCloud\Hook\Typo3CacheManager:
    public: true