services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Fr\BmgResubmission\:
    resource: '../Classes/*'
    exclude: ['../Classes/Domain/{DTO,Enum}']

  Fr\BmgResubmission\Command\MonitorCommand:
    tags:
      - name: 'console.command'
        command: 'bmg:resubmission:monitor'
        description: 'Send mails for outdated Page to Maintainer'
        hidden: false
        schedulable: true