services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  CPSIT\CpsMyraCloud\:
    resource: '../Classes/*'
    exclude: ['../Classes/Domain/{DTO,Enum}']

  CPSIT\CpsMyraCloud\ButtonBar\ExternalClearCacheButtonBarItemProvider:
    public: true

  CPSIT\CpsMyraCloud\Controller\ExternalClearCacheController:
    public: true

  CPSIT\CpsMyraCloud\FileList\FileListHook:
    public: true

  CPSIT\CpsMyraCloud\DataHandler\DataHandlerHook:
    public: true

  CPSIT\CpsMyraCloud\Command\MyraCloudClearCommand:
    tags:
      - name: 'console.command'
        command: 'myracloud:clear'
        description: 'TYPO3-MyraCloud Interface'
        hidden: false
        schedulable: false
