services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  CPSIT\CpsMyraCloud\:
    resource: '../Classes/*'
    exclude: ['../Classes/Domain/{DTO,Enum}']

  CPSIT\CpsMyraCloud\ButtonBar\ExternalClearCacheButtonBarItemProvider:
    public: true

  CPSIT\CpsMyraCloud\Controller\ExternalClearCacheController:
    public: true
